# Generated by Django 4.0.4 on 2023-03-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'active'), ('in_progress', 'in_progress'), ('collected', 'collected')], max_length=20)),
                ('previous_jobs_count', models.IntegerField()),
                ('amount_due', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
    ]
